EmployeesManagement/Models/Employee.cs
using System.ComponentModel;

namespace EmployeesManagement.Models
{
    public class Employee : UserActivity
    {
        public int Id { get; set; }
        public string EmpNo { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        public string FullName => $"{FirstName} {MiddleName} {LastName}";
        public string EmailAddress { get; set; }
        [DisplayName("Phone Number")]
        public int PhoneNumber { get; set; }
        [DisplayName("Country Name")]
        public int? CountryId { get; set; }
        public Country Country { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        [DisplayName("Department Name")]
        public int? DepartmentId { get; set; }
        public Department Department { get; set; }
        [DisplayName("Designation Name")]
        public int? DesignationId { get; set; }
        public Designation Designation { get; set; }
        [DisplayName("Gender")]
        public int? GenderId { get; set; }
        public SystemCodeDetail Gender { get; set; }
        [DisplayName("Employee Photo")]
        public string? Photo { get; set; }
        [DisplayName("Employement Date")]
        public DateTime? EmployementDate { get; set; }
        public int? StatusId { get; set; }
        public SystemCodeDetail Status { get; set; }
        public DateTime? InactiveDate { get; set; }
        public int? CauseOfInactivityId { get; set; }
        public SystemCodeDetail CauseOfInactivity { get; set; }
        public DateTime? TerminationDate { get; set; }
        public int? ReasonforterminationId { get; set; }
        public SystemCodeDetail Reasonfortermination { get; set; }
        [DisplayName("Bank Name")]
        public int? BankId { get; set; }
        public Bank Bank { get; set; }
        [DisplayName("Bank Account No")]
        public string? BankAccountNo {  get; set; }

        [DisplayName("International Bank Account No")]
        public string? IBAN { get; set; }
        [DisplayName("SWIFT Code")]
        public string? SWIFTCode { get; set; }
        [DisplayName("N.S.S.F No")]
        public string? NSSFNO { get; set; }
        [DisplayName("NHIF No")]
        public string? NHIF { get; set; }
        [DisplayName("Company Email")]
        public string? CompanyEmail { get; set; }
        [DisplayName("KRA PIN")]
        public string? KRAPIN { get; set; }
        [DisplayName("Passport No")]
        public string? PassportNo { get; set; }
        [DisplayName("Employment Terms")]
        public int? EmploymentTermsId { get; set; }
        public SystemCodeDetail EmploymentTerms { get; set; }
        [DisplayName("Allocated Leave Balance")]
        public Decimal? AllocatedLeaveDays { get; set; }
        [DisplayName("Leave Balance")]
        public Decimal? LeaveOutStandingBalance { get; set; }
        [DisplayName("Pays Tax")]
        public bool? PaysTax { get; set; }

        [DisplayName("Disability Type")]
        public int? DisabilityId { get; set; }
        public SystemCodeDetail Disability { get; set; }

        public string? DisabilityCertificate { get; set; }

    }
}

EmployeesManagement/ViewModels/employeeViewModel.cs
using EmployeesManagement.Models;
using System.ComponentModel;

namespace EmployeesManagement.ViewModels
{
    public class employeeViewModel
    {
        public int Id { get; set; }
        public string EmpNo { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        public string FullName => $"{FirstName} {MiddleName} {LastName}";
        public string EmailAddress { get; set; }
        [DisplayName("Phone Number")]
        public int PhoneNumber { get; set; }
        [DisplayName("Country Name")]
        public int? CountryId { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        [DisplayName("Department Name")]
        public int? DepartmentId { get; set; }
        [DisplayName("Designation Name")]
        public int? DesignationId { get; set; }
        [DisplayName("Gender")]
        public int? GenderId { get; set; }
        [DisplayName("Employee Photo")]
        public string? Photo { get; set; }
        [DisplayName("Employement Date")]
        public DateTime? EmployementDate { get; set; }
        public int? StatusId { get; set; }
        public DateTime? InactiveDate { get; set; }
        public int? CauseOfInactivityId { get; set; }
        public SystemCodeDetail CauseOfInactivity { get; set; }
        public DateTime? TerminationDate { get; set; }
        public int? ReasonforterminationId { get; set; }
        [DisplayName("Bank Name")]
        public int? BankId { get; set; }
        [DisplayName("Bank Account No")]
        public string? BankAccountNo { get; set; }

        [DisplayName("International Bank Account No")]
        public string? IBAN { get; set; }
        [DisplayName("SWIFT Code")]
        public string? SWIFTCode { get; set; }
        [DisplayName("N.S.S.F No")]
        public string? NSSFNO { get; set; }
        [DisplayName("NHIF No")]
        public string? NHIF { get; set; }
        [DisplayName("Company Email")]
        public string? CompanyEmail { get; set; }
        [DisplayName("KRA PIN")]
        public string? KRAPIN { get; set; }
        [DisplayName("Passport No")]
        public string? PassportNo { get; set; }
        [DisplayName("Employment Terms")]
        public int? EmploymentTermsId { get; set; }
        [DisplayName("Allocated Leave Balance")]
        public Decimal? AllocatedLeaveDays { get; set; }
        [DisplayName("Leave Balance")]
        public Decimal? LeaveOutStandingBalance { get; set; }
        [DisplayName("Pays Tax")]
        public bool? PaysTax { get; set; }

        [DisplayName("Disability Type")]
        public int? DisabilityId { get; set; }

        public string? DisabilityCertificate { get; set; }

        public Employee Employee { get; set; }

        public List<Employee> Employees { get; set; }
    }
}

EmployeesManagement/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeesManagement.Data;
using EmployeesManagement.Models;
using System.Security.Claims;
using EmployeesManagement.ViewModels;
using AutoMapper;

namespace EmployeesManagement.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;
        public EmployeesController(ApplicationDbContext context, IConfiguration configuration, IMapper mapper)
        {
            _context = context;
            _configuration = configuration;
            _mapper = mapper;
        }

        // GET: Employees
        public async Task<IActionResult> Index(employeeViewModel employees)
        {
            var rawdata = _context.Employees.Include(x => x.Status).AsQueryable();
            if(!string.IsNullOrEmpty(employees.FirstName))
            {
                rawdata = rawdata.Where(x=>x.FirstName.Contains(employees.FirstName));
            }
            if(employees.PhoneNumber>0)
            {
                rawdata = rawdata.Where(x => x.PhoneNumber == employees.PhoneNumber);
            }
            if (!string.IsNullOrEmpty(employees.EmailAddress))
            {
                rawdata = rawdata.Where(x => x.EmailAddress == employees.EmailAddress);
            }
            if (!string.IsNullOrEmpty(employees.EmpNo))
            {
                rawdata = rawdata.Where(x => x.EmpNo == employees.EmpNo);
            }
            employees.Employees = await rawdata.ToListAsync();

            return View(employees);
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(x=>x.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            ViewData["BankId"] = new SelectList(_context.Banks, "Id", "Name");
            ViewData["EmploymentTermsId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "EmploymentTerms"), "Id", "Description");
            ViewData["DisabilityId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "DisabilityTypes"), "Id", "Description");
            ViewData["GenderId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "Gender"), "Id", "Description");
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name");
            ViewData["DesignationId"] = new SelectList(_context.Designations, "Id", "Name");
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(employeeViewModel newemployee,  IFormFile employeephoto)
        {
            var employee = new Employee();
            employee = _mapper.Map<Employee>(newemployee);
            if(employeephoto.Length>0)
            {
                var filename = "EmployeePhoto_" + DateTime.Now.ToString("yyyymmddhhmmss")+"_"+ employeephoto.FileName;
                var path = _configuration["Filesettings:UploadFolder"];
                var filepath = Path.Combine(path, filename);
                var stream =new FileStream(filepath, FileMode.Create);
                await employeephoto.CopyToAsync(stream);
                employee.Photo = filename;
            }
           
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            employee.CreatedById = userId;
            employee.CreatedOn = DateTime.Now;
            
            var statusId = await _context.SystemCodeDetails.Include(x=>x.SystemCode).Where(x => x.SystemCode.Code == "EmploymentStatus" && x.Code == "Active").FirstOrDefaultAsync();
            employee.StatusId = 4002;//statusId.Id;
                _context.Employees.Add(employee);
                await _context.SaveChangesAsync(userId);
            ViewData["DisabilityId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "DisabilityTypes"), "Id", "Description", employee.DisabilityId);
            ViewData["BankId"] = new SelectList(_context.Banks, "Id", "Name", employee.BankId);
                ViewData["EmploymentTermsId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "EmploymentTerms"), "Id", "Description", employee.EmploymentTermsId);
                ViewData["GenderId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "Gender"), "Id", "Description", employee.GenderId);
                ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name", employee.CountryId);
                ViewData["DesignationId"] = new SelectList(_context.Designations, "Id", "Name", employee.DesignationId);
                ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", employee.DepartmentId);
                return RedirectToAction(nameof(Index));
           
            //return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            ViewData["GenderId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "Gender"), "Id", "Description", employee.GenderId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name", employee.CountryId);
            ViewData["DesignationId"] = new SelectList(_context.Designations, "Id", "Name", employee.DesignationId);
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", employee.DepartmentId);

            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    employee.ModifiedById = userId;
                    employee.ModifiedOn = DateTime.Now;
                    _context.Update(employee);
                    await _context.SaveChangesAsync(userId);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["GenderId"] = new SelectList(_context.SystemCodeDetails.Include(x => x.SystemCode).Where(x => x.SystemCode.Code == "Gender"), "Id", "Description", employee.GenderId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name", employee.CountryId);
            ViewData["DesignationId"] = new SelectList(_context.Designations, "Id", "Name", employee.DesignationId);
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name", employee.DepartmentId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

EmployeesManagement/Views/Employees/Create.cshtml
@model EmployeesManagement.ViewModels.employeeViewModel
@{
    ViewData["Title"] = "Create";
}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Create New Employee</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Create" asp-controller="Employees" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EmpNo" class="control-label"></label>
                                <input asp-for="EmpNo" class="form-control" />
                                <span asp-validation-for="EmpNo" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="FirstName" class="control-label"></label>
                                <input asp-for="FirstName" class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="MiddleName" class="control-label"></label>
                                <input asp-for="MiddleName" class="form-control" />
                                <span asp-validation-for="MiddleName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="LastName" class="control-label"></label>
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EmailAddress" class="control-label"></label>
                                <input asp-for="EmailAddress" class="form-control" />
                                <span asp-validation-for="EmailAddress" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="GenderId" class="control-label"></label>
                                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.GenderId"></select>
                                <span asp-validation-for="GenderId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="PhoneNumber" class="control-label"></label>
                                <input asp-for="PhoneNumber" class="form-control" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CountryId" class="control-label"></label>
                                <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
                                <span asp-validation-for="CountryId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DateOfBirth" class="control-label"></label>
                                <input asp-for="DateOfBirth" class="form-control" />
                                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EmployementDate" class="control-label"></label>
                                <input asp-for="EmployementDate" class="form-control" />
                                <span asp-validation-for="EmployementDate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Address" class="control-label"></label>
                                <input asp-for="Address" class="form-control" />
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DepartmentId" class="control-label"></label>
                                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                                <span asp-validation-for="DepartmentId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DesignationId" class="control-label"></label>
                                <select asp-for="DesignationId" class="form-control" asp-items="ViewBag.DesignationId"></select>
                                <span asp-validation-for="DesignationId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="BankId" class="control-label"></label>
                                <select asp-for="BankId" class="form-control" asp-items="ViewBag.BankId"></select>
                                <span asp-validation-for="BankId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="BankAccountNo" class="control-label"></label>
                                <input asp-for="BankAccountNo" class="form-control"></input>
                                <span asp-validation-for="BankAccountNo" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="IBAN" class="control-label"></label>
                                <input asp-for="IBAN" class="form-control"></input>
                                <span asp-validation-for="IBAN" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="SWIFTCode" class="control-label"></label>
                                <input asp-for="SWIFTCode" class="form-control"></input>
                                <span asp-validation-for="SWIFTCode" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="NSSFNO" class="control-label"></label>
                                <input asp-for="NSSFNO" class="form-control"></input>
                                <span asp-validation-for="NSSFNO" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="NHIF" class="control-label"></label>
                                <input asp-for="NHIF" class="form-control"></input>
                                <span asp-validation-for="NHIF" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CompanyEmail" class="control-label"></label>
                                <input asp-for="CompanyEmail" class="form-control"></input>
                                <span asp-validation-for="CompanyEmail" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="KRAPIN" class="control-label"></label>
                                <input asp-for="KRAPIN" class="form-control"></input>
                                <span asp-validation-for="KRAPIN" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="PassportNo" class="control-label"></label>
                                <input asp-for="PassportNo" class="form-control"></input>
                                <span asp-validation-for="PassportNo" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EmploymentTermsId" class="control-label"></label>
                                <select asp-for="EmploymentTermsId" class="form-control" asp-items="ViewBag.EmploymentTermsId"></select>
                                <span asp-validation-for="EmploymentTermsId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DisabilityId" class="control-label"></label>
                                <select asp-for="DisabilityId" class="form-control" asp-items="ViewBag.DisabilityId"></select>
                                <span asp-validation-for="DisabilityId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DisabilityCertificate" class="control-label"></label>
                                <input asp-for="DisabilityCertificate" class="form-control"></input>
                                <span asp-validation-for="DisabilityCertificate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Photo" class="control-label"></label>
                                <input asp-for="Photo" id="photo" name="employeephoto" class="form-control employeephoto" type="file" accept=".png,.jpg,.jpeg"></input>
                                <span asp-validation-for="Photo" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card-footer">
                                <div class="clearfix">
                                    <a asp-action="Index" class="btn btn-danger push-left">Back to List</a>
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>

</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}