EmployeesManagement/ViewModels/ProfileViewModel.cs
using EmployeesManagement.Models;
using System.ComponentModel;

namespace EmployeesManagement.ViewModels
{
    public class ProfileViewModel
    {
        public ICollection<SystemProfile> Profiles { get; set; }

        public ICollection<int> RolesRightsIds { get; set; }

        public int[] Ids {  get; set; }

        [DisplayName("Role")]
        public string RoleId { get; set; }

        [DisplayName("System Task")]
        public int TaskId { get; set; }
    }
}

EmployeesManagement/Controllers/ProfilesController.cs
using EmployeesManagement.Data;
using EmployeesManagement.Models;
using EmployeesManagement.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace EmployeesManagement.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ProfilesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<ActionResult> Index()
        {
            var tasks = new ProfileViewModel();
            var roles = await _context.Roles.OrderBy(x => x.Name).ToListAsync();
            ViewBag.Roles = new SelectList(roles, "Id", "Name");
            var systemtasks = await _context.SystemProfiles.
                Include("Children.Children.Children")
                //.Where(t=> t.ProfileId == null)
                .OrderBy(x => x.Order)
                .ToListAsync();

            ViewBag.Tasks = new SelectList(systemtasks, "Id", "Name");

            return View(tasks);
        }

        public async Task<ActionResult> AssignRights(ProfileViewModel vm)
        {
            var UserId= User.FindFirstValue(ClaimTypes.NameIdentifier);
            var roles = new RoleProfile
            {
                TaskId = vm.TaskId,
                RoleId = vm.RoleId
            };
            _context.RoleProfiles.Add(roles);
            await _context.SaveChangesAsync(UserId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> UserRights(string id)
        {
            var tasks = new ProfileViewModel();
            tasks.RoleId = id;
            tasks.Profiles = await _context.SystemProfiles.
                Include(s=>s.Profile).
                Include("Children.Children.Children")
                .OrderBy(x => x.Order)
                .ToListAsync();

            tasks.RolesRightsIds= await _context.RoleProfiles.Where(x=>x.RoleId==id).Select(r=> r.TaskId).ToListAsync();

            return View(tasks);
        }

        [HttpPost]
        public async Task<ActionResult> UserRights(string id,ProfileViewModel vm)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var allrights = await _context.RoleProfiles.Where(x=>x.RoleId==id).ToListAsync();
            _context.RoleProfiles.RemoveRange(allrights);
            await _context.SaveChangesAsync(userId);

            foreach (var taskId in vm.Ids)
            { 
                var role = new RoleProfile
                { 
                    TaskId = taskId,
                    RoleId = id
                };

                _context.RoleProfiles.Add(role);
                await _context.SaveChangesAsync(userId);
            }
            return View(vm);
        }
            
            
    }
}

EmployeesManagement/Views/Profiles/Index.cshtml
@model EmployeesManagement.ViewModels.ProfileViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Assign User Roles</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
<div class="row">
    <div class="col-md-12">
        <form asp-action="AssignRights" asp-controller="Profiles">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="RoleId" class="control-label"></label>
                                <select asp-for="RoleId" class="form-control" asp-items="ViewBag.Roles"></select>
                                <span asp-validation-for="RoleId" class="text-danger"></span>
                            </div>
                        </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TaskId" class="control-label"></label>
                                <select asp-for="TaskId" class="form-control" asp-items="ViewBag.Tasks"></select>
                                <span asp-validation-for="TaskId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @* <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span> *@
                    </div>
                </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i>Assign Rights</button>
                        </div>
                </div>
        </form>
    </div>

</div>
</div>
</div>

EmployeesManagement/Views/Profiles/UserRights.cshtml
@model EmployeesManagement.ViewModels.ProfileViewModel

@{
    ViewData["Title"] = "Assign User Rights";
}


<div class="card">

    <!-- /.card-header -->
    <div class="card-body">
        <div class="table-responsive">
            <form asp-action="UserRights" asp-controller="Profiles" method="post">
                <input type="hidden" name="id" value="@Model.RoleId" />
                <table id="example1" class="table table-bordered table-striped table-hover table-fixed-header">
                    <thead class="header" style="margin: 0px auto; width: 1280px;">
                        <tr>
                            <th>
                                Module
                            </th>
                            <th>
                                SubModule
                            </th>
                            <th>
                                Actions
                            </th>
                            <th>
                                Assign Right
                            </th>
                          
                        </tr>
                    </thead>
                    <tbody>
                        @if(Model.Profiles != null)
                        {
                            @foreach(var module in Model.Profiles.Where(x=> x.ProfileId == null))
                            {
                                <tr>
                                    <th>
                                    @module.Name
                                    @if(module.Children.Any())
                                        {
                                            @foreach(var submodule in module.Children)
                                            {
                                                <tr>
                                                    <th></th>
                                                    <th>
                                                        <input type="hidden" name="RolesProfilesIds[]" value="@submodule.Id" />
                                                    </th>
                                                </tr>
                                                    @foreach (var actions in submodule.Children)
                                                    {
                                                        <tr>
                                                        <th></th>
                                                        <th></th>
                                                        <td>@actions.Name</td>
                                                        <td>
                                                            @if(Model.RolesRightsIds.Contains(actions.Id))
                                                            {
                                                                <label class="">
                                                                    <input type="checkbox" name="Ids[]" value="@actions.Id" checked="checked" />
                                                                </label>
                                                            }
                                                            else
                                                            {
                                                                <label class="">
                                                                    <input type="checkbox" name="Ids[]" value="@actions.Id"  />
                                                                </label>
                                                            }
                                                        </td>
                                                        </tr>
                                                    }
                                                
                                            }
                                        }
                                    </th>
                                </tr>
                                
                            }
                        }
                    </tbody>
                </table>

                <div class="form-group">
                    <div class="col-md-12">
                        <div class="card-footer">
                            <div class="clearfix">
                                <a asp-action="Index" class="btn btn-danger push-left">Back to List</a>
                                <input type="submit" value="Assign Rights" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>